### ISSUE TITLE
Create Question Paper Routes

### ISSUE THREAD

**Issue by meet59patel** [meet59patel/Group3-Yosemite-backend#3]
- [x] Get all question papers created by a Faculty, based on Faculty ID
  - [x] Sorted from new to old
- [x] Create new question paper

**Comment by meet59patel** [comment]
Expected Routes:
@ GET `/questionpaper/faculty/<id:facultyId>`  => Get all question papers created by a faculty
@ POST `/questionpaper/`    => Create new question paper

**Comment by chirag1911** [comment]
I've created all the routers related to questionpaper.
